[project]
name = "praman-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.5",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "indic-transliteration>=2.3.82",
    "jinja2>=3.1.6",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "rapidfuzz>=3.14.6",
    "splink>=4.0.17",
    "uvicorn[standard]>=0.54.0",
]
